# unzip download/300VW_Dataset_2015_12_14.zip -d download
# unzip download/300W.zip -d download
# unzip download/afw.zip -d download/afw
# unzip download/helen.zip -d download/helen
# unzip download/ibug.zip -d download/ibug
# unzip download/LFPW.zip -d download/LFPW
# unzip download/WFLW.zip -d download
# unzip download/300VW.zip -d download
# unzip download/AFLW2000_3D.zip -d download